### PR TITLE
Use "data-" prefix for "date-format" attribute name

### PR DESCRIPTION
**Pull request by toddwelstein**
React doesn't like the attribute name "date-format"; it results in an unknown-prop warning and  doesn't get rendered to the DOM. Their documentation states, "If you are trying to attach custom data to a standard DOM element, consider using a custom data attribute..."
(https://facebook.github.io/react/warnings/unknown-prop.html)

The attribute has been modified to "data-date-format", and the documentation has been updated.

### CODE REVIEW

**Comment by jcgertig** [comment]
I would rather this be an added option and not the only option. So make it work with both formats and that will be fine.

**Comment by toddwelstein** [comment]
The code and documentation have been updated to allow for either "date-format" or "data-date-format" attributes.

**Comment by jcgertig** [comment]
Nice thanks life's been hectic just got married will do a push to npm later today

**Comment by toddwelstein** [comment]
I totally understand. Thanks for getting it merged!

**Pull request merged**
